// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRCuOvwFo70cj_Y10eQS9kvqXQkrBPouQ',
    appId: '1:130978805660:android:9bbc09e2975075df3f3a59',
    messagingSenderId: '130978805660',
    projectId: 'keep-notes-8e443',
    storageBucket: 'keep-notes-8e443.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ17yF1lIcqWfY4ApISLp-8EzJuHlDOTk',
    appId: '1:130978805660:ios:034c7153637640ba3f3a59',
    messagingSenderId: '130978805660',
    projectId: 'keep-notes-8e443',
    storageBucket: 'keep-notes-8e443.appspot.com',
    iosBundleId: 'com.example.keepNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4JCbfiNik7sAQFj-6oFRLXEz5y2mgRHk',
    appId: '1:130978805660:web:63e9eae3775dbb813f3a59',
    messagingSenderId: '130978805660',
    projectId: 'keep-notes-8e443',
    authDomain: 'keep-notes-8e443.firebaseapp.com',
    storageBucket: 'keep-notes-8e443.appspot.com',
    measurementId: 'G-9SHKNXBZBJ',
  );
}
